### PR TITLE
Implement Traefik to add TLS

### PR DESCRIPTION
**Pull request by RichardBaumannLumira**

### CODE REVIEW

**Comment by RichardBaumannLumira** [comment]
@theScrabi

**Comment by RichardBaumannLumira** [comment]
@JensSchedel Can you fix and merge #3 so that your commits are not in our history?

**Comment by RichardBaumannLumira** [comment]
Also we need a secret for the email address, and potentially one to set the acme URL

**Comment by snke** [comment]
#10 could be of interest for this change, too?

**Comment by RichardBaumannLumira** [comment]
Our database was in db/, I don't know why yours is in backend/. We added db/* to the gitignore file

**Pull request merged**
